apiVersion: v1
kind: Service
metadata:
  name: frontend-bg
  namespace: gotasker
spec:
  selector:
    app: frontend-bg
    version: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
