Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.hostname = "gotasker-vm"

  # Forward VM port 8080 → host port 8443
  config.vm.network "forwarded_port",
    guest: 80,
    host: 8443,
    auto_correct: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "provision.sh"

  config.vm.synced_folder "../app", "/vagrant/app"
  config.vm.synced_folder "./www", "/vagrant/www"
  config.vm.synced_folder "./nginx", "/vagrant/nginx"
  config.vm.synced_folder "./env", "/vagrant/env"
  config.vm.synced_folder "./systemd", "/vagrant/systemd"
end
