global:
  namespace: gotasker

backend:
  replicaCount: 1
  image:
    repository: ghcr.io/galpodlipnik1/gotasker
    tag: latest
    pullPolicy: Always
  service:
    port: 8081

frontend:
  replicaCount: 3
  image:
    repository: ghcr.io/galpodlipnik1/gotasker-frontend
    tag: latest
    pullPolicy: Always
  service:
    port: 80
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

redis:
  enabled: true
  image:
    repository: redis
    tag: 7-alpine
  persistence:
    size: 1Gi

ingress:
  enabled: true
  className: nginx
  host: localhost
  tls: false

blueGreen:
  enabled: false
  activeVersion: blue # blue or green
  host: bluegreen.localhost

prometheus:
  enabled: true
  image:
    repository: prom/prometheus
    tag: v2.55.1
  persistence:
    size: 2Gi
